export const actionTypes = {
  SAVE_MOVIE_LIST: "SAVE_MOVIE_LIST",
  SAVE_MOVIE_DETAIL: "SAVE_MOVIE_DETAIL",
  SAVE_SHOWING_MOVIE_LIST: "SAVE_SHOWING_MOVIE_LIST",
  SAVE_FUTURE_MOVIE_LIST: "SAVE_FUTURE_MOVIE_LIST",
  SAVE_CINEMA_MOVIE_LIST: "SAVE_CINEMA_MOVIE_LIST",

  SAVE_USER: "SAVE_USER",

  SAVE_CINEMA_SYSTEM_LIST: "SAVE_CINEMA_SYSTEM_LIST",
  SAVE_CINEMA_SYSTEM_DETAIL: "SAVE_CINEMA_SYSTEM_DETAIL",

  SAVE_SHOWTIME_LIST: "SAVE_SHOWTIME_LIST",
  SAVE_SHOWTIME_DETAIL: "SAVE_SHOWTIME_DETAIL",
  SAVE_CINEMA_SHOWTIME_LIST: "SAVE_CINEMA_SHOWTIME_LIST",

  SAVE_SEAT_LIST: "SAVE_SEAT_LIST",
  SAVE_SEAT_DETAIL: "SAVE_SEAT_DETAIL",
  SAVE_CHOSEN_SEATS: "SAVE_CHOSEN_SEATS",

  SAVE_TICKET_LIST: "SAVE_TICKET_LIST",
  SAVE_TICKET_DETAIL: "SAVE_TICKET_DETAIL",

  SAVE_CINEMA_DETAIL: "SAVE_CINEMA_DETAIL",

  // LANGUAGE
  CHANGE_LANGUAGE: "CHANGE_LANGUAGE",
};
